version: '3.8'

services:
  web:
    build:
      context: .
    command: python Yoga/manage.py runserver 0.0.0.0:8000  # Correct path to manage.py
    volumes:
      - .:/app  # This maps the whole project directory (Yoga) to /app in the container
    expose:
      - "8000:8000"
    # depends_on:
    #   - db
    env_file:
      - .env 
    networks:
      - app-network

  # db:
  #   image: postgres:13
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_DB: yogadb
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: password
  #   networks:
  #     - app-network

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - /home/noat/Documents/Final_Project/Yoga/media:/app/media
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /home/noat/Documents/Final_Project/Yoga/staticfiles:/app/static  # Map the correct static files directory
      # - ./Yoga/staticfiles:/app/static  # Ensure that the collected static files are mapped correctly
    depends_on:
      - web
    networks:
      - app-network

# volumes:
#   postgres_data:

networks:
  app-network:
