services:
  web:
    build:
      context: .
    command: >
      sh -c "python Yoga/manage.py migrate &&
             python Yoga/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./media:/app/media  # Relative path for compatibility
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./staticfiles:/app/static  # Relative path for compatibility
    depends_on:
      - web
    networks:
      - app-network

networks:
  app-network:
