version: '3.8'

services:
  web:
    build:
      context: .
    command: python Yoga/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    expose:
      - "8000"
    env_file:
      - .env 
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - /home/noat/Documents/Final_Project/Yoga/media:/app/media
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /home/noat/Documents/Final_Project/Yoga/staticfiles:/app/static
    depends_on:
      - web
    networks:
      - app-network

networks:
  app-network:
