# Generated by Django 5.1.1 on 2024-10-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yogapose',
            name='image_path',
        ),
        migrations.AddField(
            model_name='yogapose',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='poses/'),
        ),
    ]
