# Generated by Django 5.1.1 on 2024-10-16 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yoga_app', '0003_yogasequence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yogasequence',
            name='duration',
        ),
    ]
